alias ll='ls -l'
alias vi='vim'
alias sshdev='ssh lionel@dev'
alias big_dirs='du -xk | sort -n | tail -20'
alias cable_plugged='mii-tool eth0'
alias open_ports='netstat -ntauple'
alias big_files='find / -type f -size +1000000000c'
alias vim='vim -T xterm-256color'
