#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf .git/tags.$$ --exclude=.git --languages=-javascript,sql
ctags -aRf .git/tags.$$ /usr/share/php/PHPUnit
mv .git/tags.$$ .git/tags
