if (!has('nvim'))
    set autoindent
    set autoread
    set backspace="indent,eol,start"
    set belloff="all"
    set complete-=i
    set display="lastline,msgsep"
    set encoding=utf-8
    set fillchars=vert:│,sep:│
    set history=10000
    set hlsearch
    set incsearch
    set langnoremap
    set laststatus=2
    set nrformats="bin,hex"
    set showcmd
    set smarttab
    set ttyfast
    set wildmenu
else
    setglobal scrollback=-1
endif

function! LoadDir(path) abort
    for file in split(glob(a:path . "/*.vim"), '\n')
        exe 'source' file
    endfor
endfunction

" Init the which key directory
let g:which_key_map =  {}
let g:which_key_map.t = { 'name': '+test'}
let g:which_key_map.c = { 'name': '+config'}
let g:which_key_map.i = { 'name': '+info'}
let g:which_key_map.g = { 'name': '+git'}
let g:which_key_map.f = { 'name': '+find'}
let g:which_key_map.s = { 'name': '+search'}
let g:which_key_map.b = { 'name': '+buffer'}
let g:which_key_map.e = { 'name': '+edit'}

call LoadDir("~/.vim/before")

" Initialize directories {
    function! InitializeDirectories() abort
        let dir_list = {
                    \ 'backup': 'backupdir',
                    \ 'views': 'viewdir' }

        if has('persistent_undo')
            let dir_list['undo'] = 'undodir'
        endif

        let common_dir = expand("~/.vim/")

        for [dirname, settingname] in items(dir_list)
            let directory = common_dir . dirname . '/'
            if exists("*mkdir")
                if !isdirectory(directory)
                    call mkdir(directory)
                endif
            endif
            if !isdirectory(directory)
                echo "Warning: Unable to create ".settingname." directory: " . directory
                echo "Try: mkdir -p " . directory
            else
                let directory = substitute(directory, " ", "\\\\ ", "g")
                exec "set " . settingname . "=" . directory
            endif
        endfor
    endfunction
    call InitializeDirectories()
"}

source ~/.vim/bundles.vim

" General {
    filetype plugin indent on   " Automatically detect file types.
    syntax on                   " Syntax highlighting
    scriptencoding utf-8
    set shortmess+=filmnrxoOtT          " Abbrev. of messages (avoids 'hit enter')
    set virtualedit=onemore             " Allow for cursor beyond last character
    set nospell                         " Spell checking off
    set hidden                          " Allow buffer switching without saving
    if has('clipboard')
        if has('unnamedplus')  " When possible use + register for copy-paste
            set clipboard=unnamedplus
        else         " On mac and Windows, use * register for copy-paste
            set clipboard=unnamed
        endif
    endif
    set noswapfile
    set ttimeout
    set ttimeoutlen=0
    set mouse="a"
    set shiftround
    set timeoutlen=500

    " Setting up the directories {
        set backup                  " Backups are nice ...
        if has('persistent_undo')
            set undofile                " So is persistent undo ...
            set undolevels=1000         " Maximum number of changes that can be undone
            set undoreload=10000        " Maximum number lines to save for undo on a buffer reload
        endif
    " }
" }

" Vim UI {
    set tabpagemax=15               " Only show 15 tabs
    set showmode                    " Display the current mode
    set cursorline                  " Highlight current line
    set linespace=0                 " No extra spaces between rows
    set number                         " Line numbers on
    set showmatch                   " Show matching brackets/parenthesis
    set winminheight=0              " Windows can be 0 line high
    set ignorecase                  " Case insensitive search
    set smartcase                   " Case sensitive when uc present
    set wildmode=list:longest,full  " Command <Tab> completion, list matches, then longest common part, then all.
    set scrolljump=5                " Lines to scroll when cursor leaves screen
    set scrolloff=3                 " Minimum lines to keep above and below cursor
    set list
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:␣ " Highlight problematic whitespace
    set completeopt=noinsert,menuone,noselect " don't insert automatically, display even when there is only one option, don't select automatically
    set complete-=t

    set guifont=DroidSansMono\ Nerd\ Font\ 10
    let &t_ut='' " fix background issues
    set t_Co=256
    set fillchars=fold:\ 
    set termguicolors
    colorscheme tokyonight
" }

" Formatting {
    set nowrap                      " Do not wrap long lines
    set shiftwidth=4                " Use indents of 4 spaces
    set expandtab                   " Tabs are spaces, not tabs
    set tabstop=4                   " An indentation every four columns
    set softtabstop=4               " Let backspace delete indent
    set nojoinspaces                " Prevents inserting two spaces after punctuation on a join (J)
    set splitright                  " Puts new vsplit windows to the right of the current
    set splitbelow                  " Puts new split windows to the bottom of the current

    function! TrimWhiteSpace() abort
        %s/\s*$//
        ''
    endfunction
" }

" Folding {
"
    function! CleanLine(line) abort
        let comment = substitute(&commentstring, '%s', '', '')
        let line = substitute(a:line, comment, '', '')
        let line = substitute(line, "^\\s*", '', '')
        let line = substitute(line, "\\s*$", '', '')
        return line
    endfunction
    function! MyFoldText() abort "{
        let line = CleanLine(getline(v:foldstart))
        let dashes = repeat(v:folddashes, v:foldlevel)
        return sprintf(' %s %s (%d lines)', dashes, line, v:foldend - v:foldstart)
    endfunction "}
    set foldtext=MyFoldText()
" }

" Key (re)Mappings {
    nnoremap Y y$

    " better fold move commands
    nnoremap zk zk[z
    nnoremap zK zk
    nnoremap zJ zj]z

    " Visual shifting (does not exit Visual mode)
    vnoremap < <gv
    vnoremap > >gv

    " Allow using the repeat operator with a visual selection (!)
    " http://stackoverflow.com/a/8064607/127816
    vnoremap . :normal .<CR>

    " Some helpers to edit mode
    " http://vimcasts.org/e/14
    cnoremap %% <C-R>=expand('%:h')<cr>

    " Disable arrows
    noremap  <up> <nop>
    noremap  <down> <nop>
    noremap  <left> <nop>
    noremap  <right> <nop>

    let mapleader = "\<Space>"

    inoremap jj <Esc>

    nnoremap j gj
    nnoremap k gk

    " move easily through buffers
    nnoremap <C-h> :bp<cr>
    nnoremap <C-l> :bn<cr>

    "switch to test file
    nnoremap <C-t> :A<cr>

    "switch to previous buffer
    nnoremap <C-j> :b#<cr>

	"switch to buffer
	nnoremap gb :ls<cr>:b

    "Edit vim config
    nnoremap <leader>ce :e ~/.vim/vimrc<cr>
    let g:which_key_map.c.e = 'edit-config'

    "Reloads vim config
    nnoremap <leader>cl :source $MYVIMRC<cr>
    let g:which_key_map.c.l = 'load-config'


    "Alias to vim folder
    cnoremap dvim <C-R>=expand('~/.vim')<cr>

    "copy/paste from system clipboard
    vnoremap <Leader>y "+y
    vnoremap <Leader>d "+d
    nnoremap <Leader>p "+p
    nnoremap <Leader>P "+P
    vnoremap <Leader>p "+p
    vnoremap <Leader>P "+P

    "terminal mode escape
    tnoremap <Esc> <C-\><C-n>

    cnoremap vterm vsplit term://
    cnoremap sterm split term://

    nnoremap <Leader>tf :Test<CR>
    nnoremap <Leader>ts :Tests<CR>
    nnoremap <Leader>tv :Testv<CR>

    nnoremap <Leader>bn <Cmd>bn
    let g:which_key_map.b.n = 'buffer-next'
    nnoremap <Leader>bp <Cmd>bp
    let g:which_key_map.b.p = 'buffer-previous'
    nnoremap <Leader>bd <Cmd>bd
    let g:which_key_map.b.d = 'buffer-delete'
    nnoremap <Leader>bw <Cmd>bw
    let g:which_key_map.b.w = 'buffer-wipeout'
    nnoremap <Leader>bo <Cmd>Bonly
    let g:which_key_map.b.o = 'buffer-only'
    nnoremap <Leader>ba <Cmd>A
    let g:which_key_map.b.a = 'buffer-alternate'
    nnoremap <Leader>b# <Cmd>b#
    let g:which_key_map.b['#'] = 'buffer-switch'
" }

" Open Quickfix window when text is written in it {
    augroup quickfix
        autocmd!
        autocmd QuickFixCmdPost * call asyncrun#quickfix_toggle(8, 1)
    augroup END
" }

" Source every plugin configs {
    call LoadDir("~/.vim/pluginconf")
" }

" Normal Vim omni-completion {
augroup filetypes
  autocmd!
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
augroup END
" }
" length matters {
    let g:lengthmatters_start_at_column = 120
" }

call LoadDir("~/.vim/local")
